# Generated by Django 5.1.4 on 2025-09-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='The name of the field to check', max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('contains', 'Contains'), ('in', 'In'), ('not_in', 'Not In'), ('belongs_to', 'Belongs To')], max_length=20)),
                ('value', models.CharField(help_text='The value to compare against', max_length=255)),
                ('negate', models.BooleanField(default=False, help_text='Negate the condition')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='organization.rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('organization.Department', 'Department'), ('organization.SubDepartment', 'SubDepartment'), ('target.Target', 'Target'), ('collection.Collection', 'Collection')], max_length=100)),
                ('field_name', models.CharField(blank=True, help_text='Specific field to apply rule to (leave blank for all fields)', max_length=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='organization.rule')),
            ],
        ),
    ]
